### ISSUE TITLE
2s delay/lag?

### ISSUE THREAD

**Issue by rkarlsba** [andresgottlieb/soundcast#11]
Hi
I just got a chromecast audio and plugged it in, configured it, and it works, but… with audiocast it gives me a 2s delay or lag, making it efficiently useless for things like movies. Any idea why this happens?
Running this on a 4YO macbook pro 17" with an i7 and 4GB memory, mostly idle.
thanks
roy

**Comment by andresgottlieb** [comment]
Hi, 

  Unfortunately, I believe this is a limitation of the Chromecast protocol. As far as I know, Chromecasts are not meant for realtime streaming to that level of sync. This behavior could be also caused, in part, by the webcast-osx-audio underlying module, which uses lame to encode system audio on the fly as an mp3 over http stream.

I don't really visualize a solution to this problem, but maybe you can find out more. A relevant question here would be: how much audio lag do you experience when casting a tab from Google Chrome (using the  Chrome extension)?

**Comment by rkarlsba** [comment]
About 400ms delay with chrome (or so, playing something from youtube), and about 2600ms with audacity through soundcast, so probably not only a protocol issue. 400ms is bad enough, but VLC can handle audio delays, but 2600ms isn't very much fun

**Comment by RockyMM** [comment]
Safari playing something from YouTube gives me more than 2secs lag. I have MBP 15" late 2014.

**Comment by rosmo** [comment]
Chromecast Audio gives me about 2 seconds lag. MP3 frames are typically 26 ms per frame. These may or may not be independent of each other and apparently worst case scenario is that 9 previous frames are needed for decoding. So inherent latency is 26-234 ms. There's probably some buffering going on somewhere, which considering the bitrate of audio could be disabled or at least minimized...
