### ISSUE TITLE
Interference between computers?

### ISSUE THREAD

**Issue by larsf** [andresgottlieb/soundcast#12]
Hi,
I have 2 computers with your software installed. On the computer I first installed it on, things work fine, until I got to the second computer and select "cast to" as soon as the "Refresh Chromecast" item comes up, audio from the first computer stops. And stays stopped until I do a "stop cast" and start over again on that machine. The second machine has never been able to see any chrome cast devices, even after I stop casting on the first one.. It always shows the "Refresh Chromecast" menu item...

**Comment by andresgottlieb** [comment]
@larsf, that's really interesting.. I'm trying to think about what could cause this but really don't know.

If anyone else has 2 computers and could replicate this it, please let me know here.

**Comment by larsf** [comment]
Hi Andres, 
Do you  have a detailed writeup on how to run this from the command line? When I tried "node main.js" I just got into an endless loop of missing dependencies - even though I set the NPN_MODULE_PATH variable. I am pretty green to the node environment but not to debugging in general :-)

**Comment by larsf** [comment]
Just a quick update. 1) I reinstalled soundcast on the computer that only showed "refresh" and that helped. It now sees the device and I am able to play music from either. On the machine I had to reinstall on, node core dumps often:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	0x000008d58950d699 0 + 9713224832665
1   ???                           	0x000008d589506276 0 + 9713224802934
2   node                          	0x00000001001884e7 v8::internal::Invoke(bool, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*, bool*) + 423
3   node                          	0x000000010012d96f v8::Function::NewInstance(int, v8::Handle<v8::Value>*) const + 527
4   audio.node                    	0x0000000100bf2a45 AudioInput::EmitMessage(uv_async_s*, int) + 341
5   node                          	0x000000010043ef18 uv__async_event + 64
6   node                          	0x000000010043f09c uv__async_io + 136
7   node                          	0x000000010044bb74 uv__io_poll + 1503
8   node                          	0x000000010043f4e1 uv_run + 239
9   node                          	0x00000001003f916c node::Start(int, char**) + 365

**Comment by andresgottlieb** [comment]
Hi @larsf ,

  Sorry for not answering this before.

  It's great news you managed to fix that weird problem.

  About the node core dumping:

  1. Does that error kill the sound casting?
  2. What version of node are you using?

**Comment by larsf** [comment]
node version is 0.10.38

**Comment by larsf** [comment]
Yes when node crashes, soundcasting stops. I have to tell soundcast to stop  casting and then
