### ISSUE TITLE
No audio from Chromecast Audio

### ISSUE THREAD

**Issue by rosmo** [andresgottlieb/soundcast#14]
Everything seems to be working, but I'm not getting any audio. Soundflower devices are visible on Audio Output and selected, Chromecast is visible in Soundcast menu, but selecting Cast makes the icon seem like it's streaming but nothing is heard from speakers. I tried running Electron from commandline but it doesn't really give any extra debug information:

```
$ ./Electron
Soundflower (2ch)
Internal Speakers
Devices available for casting:
Rosmon audio
/bin/sh: line 0: kill: (555) - No such process
Start

```

OS X El Capitan 10.11.0. Soundflower kext is loaded:
```
$ kextstat|grep -i sound
  126    0 0xffffff7f80b05000 0x5000     0x5000     com.Cycling74.driver.Soundflower (2) 2D779840-7439-31E5-8A66-D786C3F47B75 <102 5 4 3>
```

**Comment by rosmo** [comment]
Also tried upgrading to 10.11.1, but it doesn't make a difference.

**Comment by RockyMM** [comment]
I have the same issue.

Additionally, Chromecast app is showing that nothing is being casted.

**Comment by andresgottlieb** [comment]
Hi @rosmo,

  I've just merged a pull request fixing a bug that didn't allow Chromecast names with spaces on them (I understand your Chromecast is called "Rosmon audio", right?

  Please pull the new code and try again (I haven't yet upgraded the binary, only the repo for now).

Thanks for your feedback!

cc. @RockyMM

**Comment by rosmo** [comment]
@andresgottlieb, yep, it's named that. I will try building the code later, but for now, just replacing the whitespace with underscore seems to fix the problem. Thank you!

**Comment by RockyMM** [comment]
I cannot package Soundcast myself, since I don't have Xcode.

I renamed my Chromecast and casting started to work, yay! :)

**Comment by andresgottlieb** [comment]
@rosmo and @RockyMM,

I'm glad it worked!

I built a new v1.4 binary which should work for space-named Chromecasts. Let me know if you have any problems.

**Comment by RockyMM** [comment]
Happy to report that v1.4 works nicely! :) :+1:

**Comment by andresgottlieb** [comment]
Great news! Thank you @RockyMM

**Comment by second-hand-wonder** [comment]
Just wanted to say that I had the same problem (even with the latest version) because my Chromecast name had an apostrophe in it. 

All fixed now, so thanks for an awesome app :)
