### ISSUE TITLE
Casting problem under Mavericks?

### ISSUE THREAD

**Issue by cobra872** [andresgottlieb/soundcast#16]
This hasn't worked for me yet. I've installed, uninstalled, reinstalled... everything you can think of with both soundcast and soundflower, and I can't get it to work. The soundcast application seems to find the chromecasts in my network... But when I cast to my selected chromecast, nothing happens on my tv. 

I am using Mavericks. My chromecast is the first version, and I reset the chromecast a few times.

**Comment by RockyMM** [comment]
Do you have a space in the name of your Chromecast? If so, check new v1.4 version, it fixes bug #14 .
