### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by newkek** [andresgottlieb/soundcast#17]
Hello, I just installed SoundFlower and Soundcast as mentioned in the README, but forgot that I did not install the Google Cast extension through Chrome, and after that done, it works perfect. 

The only comment I would do is to find a way to detect such misconfiguration and indicating it at some point, because here, before installing Google Cast, the app was showing me a JS exception stacktrace in the "Cast To" contextual menu, which I believe would not mean _anything_ for non-developer users. 
A pretty error message instead would be less confusing probably. 

And thanks for this app it works great!

**Comment by newkek** [comment]
Oh and also some icons look pixelized on Retina displays

**Comment by newkek** [comment]
Hmm it seems actually that this error is not related to the fact, as I described above, that I hadn't Google cast installed, since the exceptions happened again while I had Google cast installed.
 
For the record, here is what it looks like : 
<img width="1059" alt="screen shot 2015-10-29 at 11 39 34" src="https://cloud.githubusercontent.com/assets/3471564/10819480/3e46a972-7e40-11e5-9341-41d518fda2a0.png">

After a restart of the app it worked again though. If you have an idea of what could have caused this I would be curious to know.

**Comment by TapaniTseni** [comment]
I get a similar error now and then.
![screen shot 2015-10-20 at 19 16 32](https://cloud.githubusercontent.com/assets/15217080/10828329/6b63a572-7e7c-11e5-858e-f6b2dc9bce40.png)

**Comment by andresgottlieb** [comment]
Hello @newkek and @TapaniTseni,

  This looks like an error happening in the [mdns submodule](https://github.com/agnat/node_mdns) when using it to search for available Chromecasts. I'll take a look at it a try to find a solution. If you want to help too, you're 100% encouraged.

Thank you very much for your feedback!
