### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by egorvinogradov** [andresgottlieb/soundcast#2]
I installed Soundflower and put soundcast to Applications folder. When I run it, a small cat or kangaroo  icon (I coundn't recognize) quickly blinks in the menubar and disappears and nothing happens

I use OSX Yosemite 10.10.4

**Comment by andresgottlieb** [comment]
That's strange @egorvinogradov, I'm using Yosemite 10.10.4 too. The cat icon is Electron's default icon so, for some reason it's showing that one to you and crashing. Do you have any informayion on unusual configurations your system has?

**Comment by egorvinogradov** [comment]
@andresgottlieb I don't think there is anything unusual in my system. Can I debug the app somehow? Are there any logs? Or can you make a brunch with a modified app that writes logs?

**Comment by andresgottlieb** [comment]
Hi @egorvinogradov,

  Sure you can. You just have to download the code and run it (you need to have Node v0.10.x (x > 38). Building a logging version is quite complicated for me right now for lack of time, sorry.

**Comment by shadowbeam** [comment]
Didn't work for me initially, but clicking reset audio adapter solved the issue @egorvinogradov
