### ISSUE TITLE
Duplicate audio playing on computer and Chromecast

### ISSUE THREAD

**Issue by jonleung** [andresgottlieb/soundcast#21]
When I play music from spotify, it plays

- on my computer's speakers
- AND on the Chromecast

Is there a way to stop the sound coming from my computer's speakers and have it only play from the Chromecast?

If I try to mute my computer, plug in headphones, lower the volume, it lowers it on the Chromecast as well...

**Comment by andresgottlieb** [comment]
@jonleung this is awkward, probably some incompatibility with your system. With this info. I thinks it's impossible to work on this so I'm closing the issue.
