### ISSUE TITLE
No audio when the Chromecast has a quote (') character in its name

### ISSUE THREAD

**Issue by bezineb5** [andresgottlieb/soundcast#22]
Removing the quote made it work, so I guess the issue is with the parsing of the output value of chromecast-osx-audio.

Thanks!

**Comment by qianjin825** [comment]
Removed, but still no sound. In my mac's sound setting, Soundflower(2ch) or Soundflower(64ch) both show "the selected device has no output controls". :(

**Comment by bezineb5** [comment]
It's actually normal that it shows this message, as you can't control the balance or the volume.

**Comment by qianjin825** [comment]
Ok. So is there anyway to see if it has any output or troubleshoot the
output problem?

On 23 November 2015 at 01:34, bezineb5 <notifications@github.com> wrote:

> It's actually normal that it shows this message, as you can't control the
> balance or the volume.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andresgottlieb/soundcast/issues/22#issuecomment-158780114>
> .
>



-- 
- Jin.Q
