### ISSUE TITLE
Multiple Chromecasts

### ISSUE THREAD

**Issue by danielrbier** [andresgottlieb/soundcast#3]
I have multiple chromecasts on my network, and soundcast is defaulting to the wrong one. Is there a way to select the chromecast to use?

**Comment by andresgottlieb** [comment]
Hi @danielrbier,

  Yes, it defaults to the first chromecast it finds. This is a limitation of one of the modules Soundcast depends on. I'll try my best to upgrade that module and Soundcast so you can select which chromecast you want to stream to. If you have some free time in your hands, you could try contributing this yourself. This is the module: https://github.com/fardog/node-chromecast-osx-audio

**Comment by ishermandom** [comment]
According to https://github.com/fardog/node-chromecast-osx-audio/blob/master/CHANGELOG.md, it's already possible to list Chromecast devices and select one.  Is there any further missing functionality in the module, that's needed prior to being able to implement this functionality in Soundcast?

**Comment by andresgottlieb** [comment]
You're right @ishermandom, thank you for noting my mistake!

I've just added this functionality but don't have two Chromecasts to test it, would you (and @danielrbier) help me?

You can download the new version here: https://dl.dropboxusercontent.com/u/6618408/soundcast1.3.zip

Thank you!

**Comment by piquadrat** [comment]
I got two Chromecast Audio's, "Living Room" and "Bedroom". They are both visible in the switcher. When I choose "Living Room", nothing happens, but "Bedroom" works. Here's some output from the terminal

    Internal Microphone
    Internal Speakers
    Devices available for casting:
    Living Room
    Bedroom
    Start
    (at this point I chose "Living Room", then "stop casting", and finally "Bedroom")
    Connecting to device 'Bedroom'
    connected, launching app ...
    streaming at http://192.168.1.39:7531/stream.mp3
    app "Default Media Receiver" launched, loading media http://192.168.1.39:7531/stream.mp3 ...
    status broadcast playerState=BUFFERING
    media loaded playerState=BUFFERING
    status broadcast playerState=PLAYING

**Comment by piquadrat** [comment]
Ah, scratch that. Renamed "Living Room" to "LivingRoom", now it works!

**Comment by andresgottlieb** [comment]
Thank you @piquadrat , you caught an important bug! I'll try to fix it, because it would break Soundcast for everyone using a space-named Chromecast.

Kudos, and thanks again!

**Comment by rxdarkknight** [comment]
Thanks for working on this. It is very much appreciated.

**Comment by andresgottlieb** [comment]
Hi @danielrbier @ishermandom @piquadrat and @rxdarkknight,

  I've just enhanced multiple chromecast support (mainly fixed some bugs and now you can refresh available chromecasts without having to restart the app) and uploaded a new version. You can get it on the repo home (it's also v1.3, but it's a new one, sorry for the messed up versioning but the one I shared here was just for test purposes, shouldn't have been v1.3).

Thank you for any feeback, I have only one Chromecast so I haven't really been able to fully test this.

**Comment by ishermandom** [comment]
Thanks for the patch!  I do see all of my Chromecasts listed.  However, I'm currently not able to successfully cast to them.  Is there debug info that would be useful for me to provide?
