### ISSUE TITLE
Chromecast Audio doesn't show on the cast to list.

### ISSUE THREAD

**Issue by CInk-Ibrahim** [andresgottlieb/soundcast#30]
I only have chromecast audio and it is not showing on the list. It shows fine on chrome google cast app. I tried refreshing and reset audio adapter options but it still doesn't show up.

**Comment by andresgottlieb** [comment]
@CInk-Ibrahim  That's strange, have you tried this again? What's the name of your Chromecast?

**Comment by CInk-Ibrahim** [comment]
Oh it seems I needed to restart the computer after installing Soundcast. I already had Soundflower so I thought it wouldn't matter. Sorry about this.
