### ISSUE TITLE
I have multiple chromecasts and multiple groups.

### ISSUE THREAD

**Issue by richtera** [andresgottlieb/soundcast#31]
When I chose cast in 1.5 and 1.6 it always only plays to one of my devices. No matter which one I chose it's always the same device. Seems like a bug, 1.4 didn't have this problem.

**Comment by sls56789** [comment]
I have a similar problem, with 3 CC devices and 1 CC audio, Soundcast seems to select one at random, irrespective of which one I actually select from the dropdown menu.  Sometimes, it even gets the right one!  I eliminated punctuation from the CC names, though still have spaces, but no improvement.

El Capitan, Soundflower v2.0b2, Soundcast 1.6.

**Comment by sls56789** [comment]
Hacked my CC Audio name into main.js to replace the selected chromecast name variable.  Workaround - OK for now.

**Comment by mankoun** [comment]
Could you explain your workaround a bit more? I have the same issue

**Comment by sls56789** [comment]
Ok, but note that this is only good if you want to cast to one Chromecast Audio device (or one group).  If you want to be able to select from different output devices, it breaks that functionality.

Assuming you installed the app under /Applications:

Start a Terminal session, and type:
      cd /Application/soundcast.app/Contents/Resources/app
      vi main.js (or use your favourite text editor)

Now, replace the following line (line 99 in my copy):
-----------------------------------------------------------------------------------------------------------------------------
           chromecastProcess = exec(path.join(__dirname,'/node ',__dirname,'/node_modules/chromecast-osx-audio/bin/chromecast.js -n '+caption+' -p '+port+' -d "'+chromecast.name+'"'), function (err, stdout, stderr){
-----------------------------------------------------------------------------------------------------------------------------
with something like this:
-----------------------------------------------------------------------------------------------------------------------------
           chromecastProcess = exec(path.join(__dirname,'/node ',__dirname,'/node_modules/chromecast-osx-audio/bin/chromecast.js -n '+caption+' -p '+port+' -d "'+'CCAudio1'+'"'), function (err, stdout, stderr){
-----------------------------------------------------------------------------------------------------------------------------
ie. the variable chromecast.name by 'CCAudio1'

CCAudio1 is the name of my Chromecast Audio device in this case.  You should use your device name.  Don't use apostrophes in the name.  Good luck.
Hopefully this is only temporary, as I have multiple output devices I'd like to use, and not enough time to help debug it though the node_modules stuff.

**Comment by prmfrst7** [comment]
Hey guys,

First of all thanks @andresgottlieb for the amazing program!

I'm having the same issue though...
I've got two Chromecast audio, one named kitchen and the other one bedroom, both of them into a group named home. I had given them much fancier names at the beginning but I simplified them in case that would have been an issue :)
I've got a similar problem as @richtera: no matter which one I select (kitchen or bedroom), it always connects to the bedroom one... Same thing when I select the home group, only the bedroom one works.
I tried modifying the main.js file as @sls56789 advised to to but all I get is a JavaScript error message...

Any idea on how to fix this? In an ideal world I would like to be able to switch freely between the different Chromecasts, and/or stream my MacOS audio to the whole group of Chromecasts.
Thanks for this!

**Comment by mankoun** [comment]
I tried the workaround suggested by @sls56789 and the sound comes from a different Chromecast than before but again not the group I hardcoded.

**Comment by sls56789** [comment]
Did you restart the app?  or even a reboot might be better.

**Comment by sls56789** [comment]
@prmfrst7 - make sure you get that sequence of quotes right: "'+'CCAudio1'+'"'

**Comment by acheslow** [comment]
I'm having the same issue and @sls56789 's workaround isn't working with my group. Any updates to this?
