### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by 73** [andresgottlieb/soundcast#32]
Hi guys,
when I start soundcast on 10.11.2, I get this:
![screen shot 2015-12-19 at 19 17 28](https://cloud.githubusercontent.com/assets/529346/11914612/67f38b74-a685-11e5-8b42-d6cc9f28dbc4.png)

What can I do to make that better? Do you need more info? 
--73

**Comment by andresgottlieb** [comment]
@73 what's the name of your Chromecast(s)?

**Comment by 73** [comment]
*roundthehouse*. *livingroom* and *kitchen* for the audios and *tv* for the regular one.

**Comment by Magto** [comment]
I had the same problem. My Chromecast Audios was connected to the 2.4 GHz and my MacBook Pro connected to my 5GHz network. When I changed the MacBook to 2.4 GHz, the app started without any problems. I will try to connect my chromecasts to my 5GHz network and see if that works as well.

**Comment by 73** [comment]
Mine are connected to the 5GHz. I'll try 2.4GHz now.

**Comment by MadPepperJP** [comment]
I had the same problem too. I tried both 5GHz and 2.4GHz Network, but this problem occurred.

**Comment by naartjie** [comment]
Same problem here. I have just installed soundcast v1.7 via the brew cask.

As far as I can tell, I'm only running a 2.4 GHz network.

@andresgottlieb the name of the Chromecast is `Chromeo`.

**Comment by naartjie** [comment]
The problem seems to be with calling `/node_modules/chromecast-osx-audio/bin/chromecast.js -j` on [main.js line 47](https://github.com/andresgottlieb/soundcast/blob/a2172b7e00bd271042cb24eed063945a854179df/main.js#L47)

When I call it manually from terminal, this is what I get:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: dns service error: no such record
    at MDNSService.on_get_addr_info_done (/opt/homebrew-cask/Caskroom/soundcast/1.7/soundcast.app/Contents/Resources/app/node_modules/chromecast-osx-audio/node_modules/mdns/lib/resolver_sequence_tasks.js:72:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/opt/homebrew-cask/Caskroom/soundcast/1.7/soundcast.app/Contents/Resources/app/node_modules/chromecast-osx-audio/node_modules/mdns/lib/mdns_service.js:18:40)
```

Which would be consistent with the original error reported: `Unexpected Token: e`, when trying to parse the above as JSON.

@andresgottlieb any ideas?

**Comment by 73** [comment]
After I was forced to reinstall my complete box, I'm not able to reproduce the problem anymore. Thx all of you.

**Comment by MadPepperJP** [comment]
I also reinstall soundflower, and this error no longer occurs. Thanks for your response, @73.

**Comment by hugovk** [comment]
This happens for me too, and a similar problem when using the command line chromecast-osx-audio, which soundcast uses. I found a hack to fix it (see https://github.com/fardog/node-chromecast-osx-audio/issues/11), which also works here.

Edit `/Applications/soundcast.app/Contents/Resources/app/node_modules/chromecast-osx-audio/node_modules/mdns/lib/resolver_sequence_tasks.js`

and change:
```js
          if (error) {
            adr_getter.stop()
            next(error);
          } else {
```
to:
```js
          if (false) {
            adr_getter.stop()
            next(error);
          } else {
```
