### ISSUE TITLE
Can't Find My Chromecast to Connect To...

### ISSUE THREAD

**Issue by ppavicevic** [andresgottlieb/soundcast#48]
Hi,
I'm running OS 10.8. I managed to download Soundflower 1.6.5 (I think, I couldn't get the 2.0 to install on my machine. But 1.6.5. did, and I'm able to switch my computers INPUT and OUTPUTS to Soundflower 2 channel. 

I also downloaded and installed Soundcast and I get the icon to appear on the up top bar. However, it can't seem to find my chromecast audio. I can stream just fine through Chrome and the extension, however I'd like to try and fix this to eliminate the need for the Chrome. 

Any ideas? I feel like it's a simple tweak away. I've tried resetting the CA and then clicking "reset audio adaptor" but to no avail. 

Any help would be VERY appreciated.

Thanks!!

**Comment by JoeHill02** [comment]
Hi, I got Soundcast to find my Chromecast Audio after first using it on my ios device.  I also posted about this in the issues.

**Comment by ppavicevic** [comment]
Ok I'll try my phone. However, on my iPad have no problems at all streaming Spotify

**Comment by ppavicevic** [comment]
No dice, Still not finding any devices.

**Comment by M4SC** [comment]
Hi there, i don't know if it's still open. For me it was fixed via the firewall settings. My way to fix:
Settings -> Security -> Firewall -> Firewall Options -> Adding soundcast.app in /opt/homebrew-cask/Caskroom/soundcast/1.7/soundcast.app to the list.

After that refresh your chromecasts, confirm the popup (node wants internet access, sth. like that) and you will be able to stream. (if even that doesn't work disable invisible mode in the firewall options temporarily to connect)

Hope it helps you :)

**Comment by JoeHill02** [comment]
Thanks, M4SC--fixing the firewall settings has helped with stabilizing my computer's connection to the Chromecast. It doesn't seem to cut out randomly anymore
