### ISSUE TITLE
Playing/casting mic input instead of audio output 

### ISSUE THREAD

**Issue by mmarkman** [andresgottlieb/soundcast#5]
I just installed the app and it's working, but playing the wrong sounds. It's playing the sound from my built-in mic. I tried resetting audio adapter, no luck.

I hadn't used soundcast previously. I just installed OS X El Capitan and then installed soundcast/soundflower.

**Comment by elpagano3** [comment]
Hi, i have the same problem. Soundcast plays the sound from the mic. Recently i've updated to OS X El capitan.

**Comment by andresgottlieb** [comment]
Hi @mmarkman and @elpagano3 

I haven't upgraded to OS X El Capitan yet, but it probably has something to do with Soundflower incompatibilities on OS X El Capitan. Would you try the following and let me know if it works, so I can modify the installation guide?

1. Uninstall Soundflower following [this instructions](https://support.shinywhitebox.com/hc/en-us/articles/202751790-Uninstalling-Soundflower).
2. Install [Soundflower 2.0b2](https://github.com/mattingalls/Soundflower/releases/download/2.0b2/Soundflower-2.0b2.dmg).

(I believe you'll need to reboot after both steps)

**Comment by mmarkman** [comment]
this works @andresgottlieb

**Comment by elpagano3** [comment]
Yes, It is works! Thanks.

**Comment by andresgottlieb** [comment]
Awesome! I'll update the readme asap.
