### ISSUE TITLE
Sound Mac -> CC with delay

### ISSUE THREAD

**Issue by M4SC** [andresgottlieb/soundcast#56]
Hello,

while using this awesome app to cast the sound from a MBPr Early 2015 i noticed a delay between two and three seconds. Even between the volume changes. So for example:
Hearing music via Spotify -> Pause -> 2-3 seconds still playing -> Stops

It not the worst thing ever happened but is that normal? Or still an issue caused out of development reasons? I'm an IT student so i would expect that there is some delay through using different frameworks to get it working, but a confirmation would be nice :)

Best regards

**Comment by andresgottlieb** [comment]
FYI: https://github.com/andresgottlieb/soundcast/issues/11
