### ISSUE TITLE
Support for Audiocast

### ISSUE THREAD

**Issue by madpsy** [andresgottlieb/soundcast#63]
It would be really nice if this supported Google Audiocasts - not sure if it's feasible but if you don't ask you don't get, right? :)

**Comment by achaiah** [comment]
I would second this comment. I have several google Chromecast Audio in the house and would be awesome to cast to them!

**Comment by andresgottlieb** [comment]
@madpsy, @achaiah : it does!

**Comment by madpsy** [comment]
It certainly doesn't show my Chromecast Audio as an available device, which
is of course what I would expect to see.

**Comment by achaiah** [comment]
Same here. It does not show up in the menu (while I can audio-cast from google play and other cast-enabled apps just fine)

**Comment by madpsy** [comment]
Are we missing something @andresgottlieb? To clarify I am referring to https://www.google.co.uk/chromecast/speakers/

**Comment by madpsy** [comment]
@andresgottlieb  Are you sure? Seems it's not just me not seeing a Chromecast Audio show up in the menu.
